"""Diffusion harness devtools plugin.

Ownership model:
- Hypervisor owns real diffusion execution.
- autocapture_prime calls Hypervisor over localhost API.
- For deterministic local tests, dry-run mode can emit a local stub artifact.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
import urllib.error
import urllib.request
from typing import Any

from autocapture_nx.plugin_system.api import PluginBase, PluginContext


def _utc_run_id() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def _local_dry_run_stub(axis: str, k_variants: int) -> dict[str, Any]:
    run_id = _utc_run_id()
    run_dir = Path("artifacts") / "devtools" / "diffusion_runs" / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    _write_json(
        run_dir / "run.json",
        {
            "run_id": run_id,
            "axis": str(axis),
            "k_variants": int(k_variants),
            "dry_run": True,
            "source": "autocapture_prime.stub",
        },
    )
    variants: list[str] = []
    scorecards: list[dict[str, Any]] = []
    for idx in range(max(1, int(k_variants))):
        variant_id = f"v{idx + 1}"
        variants.append(variant_id)
        score = {
            "variant_id": variant_id,
            "status": "dry_run",
            "p1_latency_ms": None,
            "p2_tests_passed": False,
            "p3_security_passed": False,
            "p4_artifacts_complete": True,
            "notes": "dry run stub generated by autocapture_prime",
            "source": "autocapture_prime.stub",
        }
        _write_json(run_dir / f"scorecard_{variant_id}.json", score)
        scorecards.append(score)
    return {"run_id": run_id, "run_dir": str(run_dir), "variants": variants, "scorecards": scorecards, "source": "autocapture_prime.stub"}


def _post_json(url: str, payload: dict[str, Any], timeout_s: float, api_key: str) -> dict[str, Any]:
    body = json.dumps(payload).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    req = urllib.request.Request(url, data=body, method="POST", headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=float(timeout_s)) as resp:
            raw = resp.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        detail = ""
        try:
            detail = exc.read().decode("utf-8")
        except Exception:
            detail = str(exc)
        raise RuntimeError(f"hypervisor_http_{int(getattr(exc, 'code', 0) or 0)}:{detail}") from exc
    except Exception as exc:
        raise RuntimeError(f"hypervisor_unreachable:{type(exc).__name__}:{exc}") from exc
    try:
        parsed = json.loads(raw)
    except Exception as exc:
        raise RuntimeError(f"hypervisor_invalid_json:{type(exc).__name__}:{exc}") from exc
    if not isinstance(parsed, dict):
        raise RuntimeError("hypervisor_invalid_payload")
    return parsed


class DiffusionHarness(PluginBase):
    def __init__(self, plugin_id: str, context: PluginContext) -> None:
        super().__init__(plugin_id, context)

    def capabilities(self) -> dict[str, Any]:
        return {"devtools.diffusion": self}

    def run(self, axis: str, k_variants: int | None = None, dry_run: bool | None = None) -> dict[str, Any]:
        cfg = self.context.config.get("devtools", {}).get("diffusion", {})
        k = k_variants if k_variants is not None else cfg.get("k_variants", 1)
        dry = dry_run if dry_run is not None else cfg.get("dry_run", True)
        # Local dry-run stub preserves deterministic testability without requiring
        # Hypervisor runtime. Real execution is delegated to Hypervisor.
        if bool(dry):
            return _local_dry_run_stub(axis=str(axis), k_variants=int(k))
        base_url = str(
            cfg.get("hypervisor_base_url")
            or os.environ.get("AUTOCAPTURE_HYPERVISOR_BASE_URL")
            or "http://127.0.0.1:7411"
        ).strip()
        path = str(cfg.get("hypervisor_diffusion_path") or "/v1/autocapture/devtools/diffusion").strip()
        timeout_s = float(cfg.get("hypervisor_timeout_s", 120.0))
        api_key = str(
            cfg.get("hypervisor_api_key")
            or os.environ.get("AUTOCAPTURE_HYPERVISOR_API_KEY")
            or ""
        ).strip()
        if not base_url.startswith("http://127.0.0.1"):
            raise RuntimeError(f"invalid_hypervisor_base_url:{base_url}")
        endpoint = f"{base_url.rstrip('/')}/{path.lstrip('/')}"
        payload = {
            "axis": str(axis),
            "k_variants": int(k),
            "dry_run": False,
            "caller": "autocapture_prime.devtools.diffusion",
        }
        result = _post_json(endpoint, payload, timeout_s=timeout_s, api_key=api_key)
        if not bool(result.get("ok", True)):
            raise RuntimeError(
                f"hypervisor_diffusion_failed:endpoint={endpoint}:detail={result.get('error') or result.get('detail') or 'unknown'}"
            )
        result.setdefault("source", "hypervisor.api")
        result.setdefault("endpoint", endpoint)
        return result


def create_plugin(plugin_id: str, context: PluginContext) -> DiffusionHarness:
    return DiffusionHarness(plugin_id, context)
