param(
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Ensure-Dir {
    param([Parameter(Mandatory = $true)][string]$PathValue)
    if (-not (Test-Path -LiteralPath $PathValue)) {
        New-Item -ItemType Directory -Path $PathValue -Force | Out-Null
    }
}

function Add-ProfileHook {
    param(
        [Parameter(Mandatory = $true)][string]$ProfilePath,
        [Parameter(Mandatory = $true)][string]$HookLine,
        [switch]$DryRunMode
    )
    $dir = Split-Path -Parent $ProfilePath
    Ensure-Dir -PathValue $dir
    if (-not (Test-Path -LiteralPath $ProfilePath)) {
        if (-not $DryRunMode) {
            Set-Content -LiteralPath $ProfilePath -Value "" -Encoding UTF8
        }
    }
    $existing = ""
    if (Test-Path -LiteralPath $ProfilePath) {
        $existing = Get-Content -LiteralPath $ProfilePath -Raw -ErrorAction SilentlyContinue
    }
    if ($existing -notmatch [regex]::Escape($HookLine)) {
        if (-not $DryRunMode) {
            Add-Content -LiteralPath $ProfilePath -Value ("`r`n" + $HookLine + "`r`n") -Encoding UTF8
        }
        return $true
    }
    return $false
}

$homeDir = [Environment]::GetFolderPath("UserProfile")
$codexDir = Join-Path $homeDir ".codex"
Ensure-Dir -PathValue $codexDir

$sharedPath = Join-Path $codexDir "codex_theme_profile.ps1"
$sharedContent = @'
# Auto-generated by tools/Enable-CodexCyberpunkTheme.ps1
# Purpose: terminal-side rendering for semantic tags emitted by Codex.

$script:CodexThemeTagMap = @{
  '[[HDR]]'   = "$([char]27)[38;5;177m"
  '[[KEY]]'   = "$([char]27)[38;5;111m"
  '[[VAL]]'   = "$([char]27)[38;5;150m"
  '[[ACCT]]'  = "$([char]27)[38;5;117m"
  '[[CSTAT]]' = "$([char]27)[38;5;81m"
  '[[CDYN]]'  = "$([char]27)[38;5;183m"
  '[[DIM]]'   = "$([char]27)[90m"
  '[[SEP]]'   = "$([char]27)[97m"
  '[[GOOD]]'  = "$([char]27)[32m"
  '[[BAD]]'   = "$([char]27)[31m"
  '[[RESET]]' = "$([char]27)[0m"
}

function Global:Convert-CodexTags {
  [CmdletBinding()]
  param(
    [Parameter(ValueFromPipeline = $true)]
    [AllowNull()]
    [object]$InputObject
  )
  begin {
    $noColor = $false
    if ($env:NO_COLOR) { $noColor = $true }
  }
  process {
    if ($null -eq $InputObject) {
      return
    }
    $line = [string]$InputObject
    if ($noColor) {
      $line = $line -replace '\[\[(HDR|KEY|VAL|ACCT|CSTAT|CDYN|DIM|SEP|GOOD|BAD|RESET)\]\]', ''
      Write-Output $line
      return
    }
    foreach ($k in $script:CodexThemeTagMap.Keys) {
      $line = $line.Replace($k, $script:CodexThemeTagMap[$k])
    }
    Write-Output $line
  }
}

function Global:Write-CodexTagged {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
    [string]$Text
  )
  process {
    ($Text | Convert-CodexTags) | ForEach-Object { Write-Host $_ }
  }
}

Set-Alias -Name codex-tags -Value Convert-CodexTags -Scope Global
Set-Alias -Name codex-write -Value Write-CodexTagged -Scope Global

$env:CODEX_TABLE_STYLE = "tags"
$env:CODEX_THEME = "cyberpunk-soft"

try {
  if ($PSVersionTable.PSVersion.Major -ge 7) {
    $esc = [char]27
    $PSStyle.Formatting.TableHeader = "$esc[38;5;177m"
    $PSStyle.Formatting.Error = "$esc[31m"
    $PSStyle.Formatting.Warning = "$esc[38;5;117m"
  }
} catch {
}
'@

if (-not $DryRun) {
    Set-Content -LiteralPath $sharedPath -Value $sharedContent -Encoding UTF8
}

$hookLine = '. "$HOME\.codex\codex_theme_profile.ps1"'

$profiles = @(
    (Join-Path $homeDir "Documents\WindowsPowerShell\profile.ps1"),
    (Join-Path $homeDir "Documents\PowerShell\profile.ps1")
)

$changes = @()
foreach ($profilePath in $profiles) {
    $added = Add-ProfileHook -ProfilePath $profilePath -HookLine $hookLine -DryRunMode:$DryRun
    $changes += [PSCustomObject]@{
        path = $profilePath
        hook_added = [bool]$added
    }
}

$payload = [PSCustomObject]@{
    ok = $true
    dry_run = [bool]$DryRun
    shared_profile = $sharedPath
    profiles = $changes
    note = "Open a new terminal. Use codex-write for tagged output, or pipe through codex-tags."
}

$payload | ConvertTo-Json -Depth 5
