from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
TOC_PATH = REPO_ROOT / "REPO_TOC.md"


def _present(paths: list[str]) -> list[str]:
    return [path for path in paths if (REPO_ROOT / path).exists()]


def _list_sorted(base: Path, pattern: str) -> list[str]:
    if not base.exists():
        return []
    return sorted(path.relative_to(REPO_ROOT).as_posix() for path in base.glob(pattern))


def _render() -> str:
    generated_utc = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    start_here = _present(
        [
            "AGENTS.md",
            "README.md",
            "docs/plans/README.md",
            "docs/contracts/real_corpus_query_readiness_contract.md",
            "docs/promptops_contract.md",
        ]
    )

    code_map = {
        "autocapture_nx": "Canonical runtime, pipeline orchestration, storage, policy gates.",
        "autocapture_plugins": "Builtin plugins and stage hooks (`builtin.processing.*`).",
        "services": "Local service adapters and supporting integrations.",
        "tools": "Operational scripts: gates, audits, fixture runners, soak utilities, report generation.",
        "tests": "Unit/integration/e2e and gate tests.",
    }

    plan_candidates = _list_sorted(REPO_ROOT / "docs" / "plans", "*.md")
    active_plans = [path for path in plan_candidates if path != "docs/plans/README.md"]
    contract_paths = _list_sorted(REPO_ROOT / "docs" / "contracts", "*")

    commands = [
        ("Full tests", "python3 tools/run_all_tests.py"),
        ("Plugin enablement gate", "python3 tools/gate_plugin_enablement.py"),
        ("Non-VLM readiness", "python3 tools/run_non_vlm_readiness.py"),
        (
            "Stage1 completeness audit",
            "python3 tools/soak/stage1_completeness_audit.py --db /mnt/d/autocapture/metadata.live.db",
        ),
        ("Strict readiness quickcheck", ".venv/bin/python tools/release_quickcheck.py --strict-exit"),
        ("PromptOps metrics", "python3 tools/promptops_metrics_report.py"),
    ]

    gate_families = [
        ("Phase gates", "tools/gate_phase*.py"),
        ("Golden/Q40", "tools/gate_q40_*.py, tools/q40.sh"),
        ("Performance/SLO", "tools/gate_perf.py, tools/gate_slo_budget.py"),
        ("Security/policy", "tools/gate_security.py, tools/gate_promptops_policy.py"),
        ("Contracts/config", "tools/gate_contract_pins.py, tools/gate_config_matrix.py"),
    ]

    lines: list[str] = []
    lines.append("# Autocapture Prime Repo TOC")
    lines.append("")
    lines.append("Purpose: fast orientation without re-scanning the entire repository.")
    lines.append("")
    lines.append(f"Generated UTC: {generated_utc}")
    lines.append("")
    lines.append("This file is generated by `tools/generate_repo_toc.py`. Do not edit manually.")
    lines.append("")
    lines.append("## Start Here (in order)")
    for idx, path in enumerate(start_here, start=1):
        lines.append(f"{idx}. `{path}`")
    lines.append("")
    lines.append("## Code Map")
    for path, desc in code_map.items():
        if (REPO_ROOT / path).exists():
            lines.append(f"- `{path}/`")
            lines.append(f"  - {desc}")
    lines.append("")
    lines.append("## Plan + Contract Map")
    lines.append(f"- Active plan docs under `docs/plans/` (excluding index): `{len(active_plans)}`")
    if active_plans:
        for path in active_plans:
            lines.append(f"- `{path}`")
    else:
        lines.append("- None currently (index-only mode).")
    lines.append(f"- Contract artifacts under `docs/contracts/`: `{len(contract_paths)}`")
    for path in contract_paths:
        lines.append(f"- `{path}`")
    lines.append("")
    lines.append("## Runtime Data Map (`/mnt/d/autocapture`)")
    lines.append("- `metadata.db`")
    lines.append("  - Capture-side source-of-truth ingest DB (actively written).")
    lines.append("- `metadata.live.db`")
    lines.append("  - Read/processing-safe live DB for pipeline work.")
    lines.append("- `derived/stage1_derived.db`")
    lines.append("  - Stage1-derived overlay store used for normalized outputs/markers.")
    lines.append("- `spool/`")
    lines.append("  - Batch handoff queue artifacts.")
    lines.append("- `media/`")
    lines.append("  - Raw screenshots/media inputs (retention constrained).")
    lines.append("- `promptops/`")
    lines.append("  - Prompt operations state and telemetry artifacts.")
    lines.append("")
    lines.append("## Query Path (high level)")
    lines.append("1. Hypervisor popup submits query.")
    lines.append("2. Query path resolves against normalized/derived corpus (no raw extraction in query path).")
    lines.append("3. PromptOps policy/shape applies.")
    lines.append("4. LLM (when available) synthesizes with citations; if unavailable, return deterministic degraded state.")
    lines.append("")
    lines.append("## Most Used Operational Commands")
    for label, command in commands:
        lines.append(f"- {label}: `{command}`")
    lines.append("")
    lines.append("## Gate Families")
    for label, pattern in gate_families:
        lines.append(f"- {label}: `{pattern}`")
    lines.append("")
    lines.append("## If You Only Need One Checklist")
    lines.append("1. Confirm services up (query/LLM/embeddings as applicable).")
    lines.append("2. Run Stage1 audit against `metadata.live.db` + `derived/stage1_derived.db`.")
    lines.append("3. Run non-VLM readiness and plugin enablement gates.")
    lines.append("4. Run query eval suite on current corpus.")
    lines.append("5. Refresh report artifacts in `docs/reports/` before declaring readiness.")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    TOC_PATH.write_text(_render(), encoding="utf-8")
    print(f"wrote {TOC_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
